/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viul;

import ia2_trab1.Empresa;
import ia2_trab1.Investidor;
import ia2_trab1.Leitor;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Bruno
 */
public class ListaEmpresas extends javax.swing.JPanel {

  DefaultListModel listaGeral = new DefaultListModel(),
               listaSelecionada = new DefaultListModel();
    Investidor i;
    Leitor l = new Leitor();
    
    public ListaEmpresas(Investidor i) {
        initComponents();
        
        this.i = i;
        preencherListaEmpresas();
        preencherListaInvestidor();
    }
    
    private void preencherListaEmpresas(){
        ArrayList<String> listaEmpresas = new ArrayList<>();
        
        try {
            l.getNomesEmpresas(1994, 1995).forEach((String empresa) -> {
                listaEmpresas.add(empresa.substring(27, 39));
            });
        } catch (Exception ex) {
            Logger.getLogger(ListaEmpresas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        listaEmpresas.stream().distinct().sorted().forEachOrdered((t) -> {
            listaGeral.addElement(t);
        });
        
        this.listaoGeral.setModel(listaGeral);
    }
    
    private void preencherListaInvestidor(){
        if (!i.getListaEmpresas().isEmpty())
            i.getListaEmpresas().forEach((e) -> {
                this.listaSelecionada.addElement(e.getNome());
            });
        
        this.listaAprovados.setModel(listaSelecionada);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbListaSelecionadas = new javax.swing.JLabel();
        lbListaGeral = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaoGeral = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        btToRight = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaAprovados = new javax.swing.JList<>();
        btToLeft = new javax.swing.JButton();
        btConfirmar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();

        lbListaSelecionadas.setText("Empresas Selecionadas");

        lbListaGeral.setText("Lista das Empresas Disponíveis");

        listaoGeral.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaoGeral.setToolTipText("");
        jScrollPane1.setViewportView(listaoGeral);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btToRight.setText("-->");
        btToRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btToRightActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(listaAprovados);

        btToLeft.setText("<--");
        btToLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btToLeftActionPerformed(evt);
            }
        });

        btConfirmar.setText("Confirmar Seleção");
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btToLeft, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(btToRight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lbListaGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbListaSelecionadas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbListaSelecionadas)
                            .addComponent(lbListaGeral))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btToRight)
                        .addGap(18, 18, 18)
                        .addComponent(btToLeft)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btToRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btToRightActionPerformed
        if (listaoGeral.getSelectedIndex() > -1)
        listaSelecionada.addElement(listaGeral.getElementAt(listaoGeral.getSelectedIndex()));
    }//GEN-LAST:event_btToRightActionPerformed

    private void btToLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btToLeftActionPerformed
        if (listaAprovados.getSelectedIndex() > -1)
        listaSelecionada.removeElement(listaSelecionada.getElementAt(listaAprovados.getSelectedIndex()));
    }//GEN-LAST:event_btToLeftActionPerformed

    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed
        if (!listaSelecionada.isEmpty()){
            ArrayList<Empresa> empresas = new ArrayList<>();
            String nome;

            for (int j = 0; j < listaSelecionada.size(); j++) {
                nome = listaAprovados.getModel().getElementAt(j);
                try {
                    empresas.add(new Empresa(nome,
                        l.interpretar(l.getHistoricoEmpresa(nome, 1994, 1995))));
            } catch (Exception ex) {
                Logger.getLogger(ListaEmpresas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        i.setListaEmpresas(empresas);
        i.getListaEmpresas().forEach((e) -> {
            try {
                i.calcularProbabilidades(e);
//                System.out.println("Saldo com a empresa " + e.getNome() +
//                    ": " + i.predicao(e));
            } catch (Exception ex) {
                Logger.getLogger(ListaEmpresas.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        i.getListaEmpresas().forEach((e) -> {
            Empresa empresa1996 = null;
            try {
                empresa1996 = new Empresa(e.getNome(),
                    l.interpretar(l.getHistoricoEmpresa(e.getNome(), 1996)));
            } catch (Exception ex) {
                Logger.getLogger(ListaEmpresas.class.getName()).log(Level.SEVERE, null, ex);
            }
//            System.out.println("SALDO DE 1996: " + i.analise(empresa1996));
        });
        }
    }//GEN-LAST:event_btConfirmarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        listaSelecionada.clear();
    }//GEN-LAST:event_btLimparActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConfirmar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btToLeft;
    private javax.swing.JButton btToRight;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbListaGeral;
    private javax.swing.JLabel lbListaSelecionadas;
    private javax.swing.JList<String> listaAprovados;
    private javax.swing.JList<String> listaoGeral;
    // End of variables declaration//GEN-END:variables
}
