package viul;

import ia2_trab1.Empresa;
import ia2_trab1.Investidor;
import ia2_trab1.Leitor;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import javax.swing.DefaultListModel;

/**
 *
 * @author Bruno
 */
public class NewJFrame extends javax.swing.JFrame {

    DefaultListModel listaGeral = new DefaultListModel(),
              listaSelecionada  = new DefaultListModel();
    Investidor investidor = new Investidor();
    Leitor l = new Leitor();
    
    public NewJFrame() {
        initComponents();
        
        String filePath = "C:\\Users\\Alessandra\\Desktop\\IA2_Trab1\\src\\cotahist\\COTAHIST.A1994";

        List<String> histValues = new ArrayList<>();
        try (Stream<String> stream = Files.lines(Paths.get(filePath))) {
            histValues = stream.collect(Collectors.toList());
        } catch (IOException e) {
            System.out.println("Error while reading file.");
        }
        
        filePath = "C:\\Users\\Alessandra\\Desktop\\IA2_Trab1\\src\\cotahist\\COTAHIST.A1995";
        try (Stream<String> stream = Files.lines(Paths.get(filePath))) {
            histValues = stream.collect(Collectors.toList());
        } catch (IOException e) {
            System.out.println("Error while reading file.");
        }        
        
        ArrayList<String> empresa = new ArrayList<>();
        histValues.forEach((h) -> {            
            empresa.add(h.substring(27, 39));
        });
        
        empresa.stream().distinct().sorted().forEachOrdered((t) -> {
            listaGeral.addElement(t);
        });
        
        this.listaoGeral.setModel(listaGeral);
        this.listaAprovados.setModel(listaSelecionada);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaoGeral = new javax.swing.JList<>();
        btToRight = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaAprovados = new javax.swing.JList<>();
        btToLeft = new javax.swing.JButton();
        btSelecionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaoGeral.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaoGeral.setToolTipText("");
        jScrollPane1.setViewportView(listaoGeral);

        btToRight.setText(">>");
        btToRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btToRightActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(listaAprovados);

        btToLeft.setText("<<");
        btToLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btToLeftActionPerformed(evt);
            }
        });

        btSelecionar.setText("Selecionar");
        btSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btToLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btToRight, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btSelecionar))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btToRight)
                        .addGap(18, 18, 18)
                        .addComponent(btToLeft)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
                        .addComponent(btSelecionar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btToRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btToRightActionPerformed
        if (listaoGeral.getSelectedIndex() > -1) {
            listaSelecionada.addElement(listaGeral.getElementAt(listaoGeral.getSelectedIndex()));
        }
    }//GEN-LAST:event_btToRightActionPerformed

    private void btToLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btToLeftActionPerformed
        if (listaAprovados.getSelectedIndex() > -1) {
            listaSelecionada.removeElement(listaSelecionada.getElementAt(listaAprovados.getSelectedIndex()));
        }
    }//GEN-LAST:event_btToLeftActionPerformed

    private void btSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelecionarActionPerformed
        ArrayList<Empresa> empresas = new ArrayList<>();
        ArrayList<String> historico = new ArrayList<>();
        String nome;
        if (!listaSelecionada.isEmpty()) {
            for (int i = 0; i < listaSelecionada.size(); i++) {
                nome = listaAprovados.getModel().getElementAt(i);
                for (int ano = 1994; ano < 1996; ano++) {
                    try {
                        historico = l.readHist(nome, ano);
                    } catch (Exception ex) {
                        Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }                
                empresas.add(new Empresa(nome, l.interpretar(historico)));
            }            
        }
        empresas.forEach((e) -> {
            e.teste();
        });
    }//GEN-LAST:event_btSelecionarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSelecionar;
    private javax.swing.JButton btToLeft;
    private javax.swing.JButton btToRight;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaAprovados;
    private javax.swing.JList<String> listaoGeral;
    // End of variables declaration//GEN-END:variables
}