package viul;

import ia2_trab1.Empresa;
import ia2_trab1.Investidor;
import ia2_trab1.Leitor;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Bruno
 */
public class ResumoIndividual extends javax.swing.JPanel {

    DefaultListModel listaModel = new DefaultListModel();
    DecimalFormat floatToString = new DecimalFormat("##.## %");
    Investidor i, dados96;
    
    public ResumoIndividual(Investidor i) {
        initComponents();
        
        this.i = i;
    }
    
    public void refresh(){
        i.getListaEmpresas().forEach((e) -> {
            listaModel.addElement(e.getNome());
        });
        
        this.listaEmpresas.setModel(listaModel);
    }
    
    void d96(){
        Leitor l = new Leitor();
        ArrayList<Empresa> empresas = new ArrayList<>();
        i.getListaEmpresas().forEach((e) -> {
            try {
                empresas.add(new Empresa(e.getNome(),
                l.interpretar(l.getHistoricoEmpresa(e.getNome(), 1996))));
            } catch (Exception ex) {
                Logger.getLogger(ResumoIndividual.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        dados96 = new Investidor();
        dados96.setListaEmpresas(empresas);
        dados96.getListaEmpresas().forEach((e) -> {
            dados96.calcularProbabilidades(e);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbEmpresasInteresse = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaEmpresas = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        pnInfo = new javax.swing.JPanel();
        lbPS = new javax.swing.JLabel();
        lbPD = new javax.swing.JLabel();
        lbPV = new javax.swing.JLabel();
        lbPC = new javax.swing.JLabel();
        pn9495 = new javax.swing.JPanel();
        lbPSD = new javax.swing.JLabel();
        lbPDD = new javax.swing.JLabel();
        lbPVD = new javax.swing.JLabel();
        lbPCD = new javax.swing.JLabel();
        lb9495 = new javax.swing.JLabel();
        lbEstimativa = new javax.swing.JLabel();
        pnEstimativa = new javax.swing.JPanel();
        lbPSE = new javax.swing.JLabel();
        lbPDE = new javax.swing.JLabel();
        lbPVE = new javax.swing.JLabel();
        lbPCE = new javax.swing.JLabel();
        btAtualizar = new javax.swing.JButton();
        pnReal = new javax.swing.JPanel();
        lbPSR = new javax.swing.JLabel();
        lbPDR = new javax.swing.JLabel();
        lbPVR = new javax.swing.JLabel();
        lbPCR = new javax.swing.JLabel();
        lbReal = new javax.swing.JLabel();

        lbEmpresasInteresse.setText("Empresas de Interesse");

        listaEmpresas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaEmpresas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaEmpresasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaEmpresas);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("NOME DA EMPRESA");

        lbPS.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPS.setText("Probabilidade de Subida:");

        lbPD.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPD.setText("Probabilidade de Descida:");

        lbPV.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPV.setText("Probabilidade de Venda:");

        lbPC.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPC.setText("Probabilidade de Compra:");

        javax.swing.GroupLayout pnInfoLayout = new javax.swing.GroupLayout(pnInfo);
        pnInfo.setLayout(pnInfoLayout);
        pnInfoLayout.setHorizontalGroup(
            pnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbPS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbPD, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
            .addComponent(lbPC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbPV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnInfoLayout.setVerticalGroup(
            pnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInfoLayout.createSequentialGroup()
                .addComponent(lbPS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPD)
                .addGap(18, 18, 18)
                .addComponent(lbPC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPV)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pn9495.setBackground(new java.awt.Color(204, 204, 204));

        lbPSD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPSD.setText("--,-- %");

        lbPDD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPDD.setText("--,-- %");

        lbPVD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPVD.setText("--,-- %");

        lbPCD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPCD.setText("--,-- %");

        javax.swing.GroupLayout pn9495Layout = new javax.swing.GroupLayout(pn9495);
        pn9495.setLayout(pn9495Layout);
        pn9495Layout.setHorizontalGroup(
            pn9495Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbPSD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbPDD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbPCD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbPVD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn9495Layout.setVerticalGroup(
            pn9495Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn9495Layout.createSequentialGroup()
                .addComponent(lbPSD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPDD)
                .addGap(18, 18, 18)
                .addComponent(lbPCD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPVD)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lb9495.setBackground(new java.awt.Color(204, 204, 204));
        lb9495.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb9495.setText("94/95");
        lb9495.setOpaque(true);

        lbEstimativa.setBackground(new java.awt.Color(204, 204, 204));
        lbEstimativa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEstimativa.setText("Estimativa");
        lbEstimativa.setOpaque(true);

        pnEstimativa.setBackground(new java.awt.Color(204, 204, 204));

        lbPSE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPSE.setText("--,-- %");

        lbPDE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPDE.setText("--,-- %");

        lbPVE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPVE.setText("--,-- %");

        lbPCE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPCE.setText("--,-- %");

        javax.swing.GroupLayout pnEstimativaLayout = new javax.swing.GroupLayout(pnEstimativa);
        pnEstimativa.setLayout(pnEstimativaLayout);
        pnEstimativaLayout.setHorizontalGroup(
            pnEstimativaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbPSE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbPDE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbPCE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbPVE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnEstimativaLayout.setVerticalGroup(
            pnEstimativaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEstimativaLayout.createSequentialGroup()
                .addComponent(lbPSE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPDE)
                .addGap(18, 18, 18)
                .addComponent(lbPCE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPVE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        pnReal.setBackground(new java.awt.Color(204, 204, 204));

        lbPSR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPSR.setText("--,-- %");

        lbPDR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPDR.setText("--,-- %");

        lbPVR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPVR.setText("--,-- %");

        lbPCR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPCR.setText("--,-- %");

        javax.swing.GroupLayout pnRealLayout = new javax.swing.GroupLayout(pnReal);
        pnReal.setLayout(pnRealLayout);
        pnRealLayout.setHorizontalGroup(
            pnRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbPSR, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
            .addComponent(lbPDR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbPCR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbPVR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnRealLayout.setVerticalGroup(
            pnRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRealLayout.createSequentialGroup()
                .addComponent(lbPSR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPDR)
                .addGap(18, 18, 18)
                .addComponent(lbPCR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPVR)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lbReal.setBackground(new java.awt.Color(204, 204, 204));
        lbReal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbReal.setText("Real");
        lbReal.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbEmpresasInteresse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btAtualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lb9495, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(pn9495, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbEstimativa, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(pnEstimativa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbReal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(pnReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lb9495)
                                    .addComponent(lbEstimativa)
                                    .addComponent(lbReal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pnInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pn9495, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pnEstimativa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pnReal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbEmpresasInteresse, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAtualizar)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        refresh();
        d96();
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void listaEmpresasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaEmpresasMouseClicked
        Empresa e;
        
        e = i.getListaEmpresas().get(this.listaEmpresas.getSelectedIndex());                
        this.lbPSD.setText(String.valueOf(floatToString.format(e.getProbSubida())));
        this.lbPDD.setText(String.valueOf(floatToString.format(e.getProbDescida())));
        this.lbPCD.setText(String.valueOf(floatToString.format(e.getProbCompra())));
        this.lbPVD.setText(String.valueOf(floatToString.format(e.getProbVenda())));
        
        e = dados96.getListaEmpresas().get(this.listaEmpresas.getSelectedIndex());                
        this.lbPSR.setText(String.valueOf(floatToString.format(e.getProbSubida())));
        this.lbPDR.setText(String.valueOf(floatToString.format(e.getProbDescida())));
        this.lbPCR.setText(String.valueOf(floatToString.format(e.getProbCompra())));
        this.lbPVR.setText(String.valueOf(floatToString.format(e.getProbVenda())));
    }//GEN-LAST:event_listaEmpresasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb9495;
    private javax.swing.JLabel lbEmpresasInteresse;
    private javax.swing.JLabel lbEstimativa;
    private javax.swing.JLabel lbPC;
    private javax.swing.JLabel lbPCD;
    private javax.swing.JLabel lbPCE;
    private javax.swing.JLabel lbPCR;
    private javax.swing.JLabel lbPD;
    private javax.swing.JLabel lbPDD;
    private javax.swing.JLabel lbPDE;
    private javax.swing.JLabel lbPDR;
    private javax.swing.JLabel lbPS;
    private javax.swing.JLabel lbPSD;
    private javax.swing.JLabel lbPSE;
    private javax.swing.JLabel lbPSR;
    private javax.swing.JLabel lbPV;
    private javax.swing.JLabel lbPVD;
    private javax.swing.JLabel lbPVE;
    private javax.swing.JLabel lbPVR;
    private javax.swing.JLabel lbReal;
    private javax.swing.JList<String> listaEmpresas;
    private javax.swing.JPanel pn9495;
    private javax.swing.JPanel pnEstimativa;
    private javax.swing.JPanel pnInfo;
    private javax.swing.JPanel pnReal;
    // End of variables declaration//GEN-END:variables
}
